-- Pumpfiction Seed Data

-- DEFAULT CHALLENGES
INSERT INTO `challenges` (`name`, `type`, `unit`, `daily_target`, `icon`, `is_active`, `is_default`, `sort_order`) VALUES
('Schritte', 'number', 'Schritte', 10000.00, '👟', 1, 1, 1),
('Push-Ups', 'number', 'Stück', 70.00, '💪', 1, 1, 2),
('Plank', 'number', 'Sekunden', 180.00, '🧘', 1, 1, 3),
('Wasser trinken', 'number', 'ml', 3000.00, '💧', 1, 1, 4),
('Kein Alkohol', 'yesno', NULL, 1.00, '🚫', 1, 1, 5),
('Clean Eating', 'yesno', NULL, 1.00, '🥗', 1, 1, 6),
('Meditation/Stretching', 'number', 'Minuten', 15.00, '🧘‍♂️', 1, 1, 7),
('Schlaf', 'number', 'Stunden', 7.00, '😴', 1, 1, 8),
('Intervallfasten', 'number', 'Stunden', 12.00, '⏱️', 1, 1, 9),
('Kalt duschen', 'yesno', NULL, 1.00, '🥶', 1, 1, 10);

-- BADGES (30)
INSERT INTO `badges` (`name`, `description`, `icon`, `condition_type`, `condition_value`, `condition_extra`, `sort_order`) VALUES
('First Blood', 'Ersten Tag vollständig geloggt', '🩸', 'first_log', 1, NULL, 1),
('Wochenkrieger', 'Eine komplette Woche alle Ziele erreicht', '⚔️', 'streak', 7, NULL, 2),
('Streak Master 7', '7-Tage-Streak erreicht', '🔥', 'streak', 7, NULL, 3),
('Streak Master 14', '14-Tage-Streak erreicht', '🔥', 'streak', 14, NULL, 4),
('Streak Master 30', '30-Tage-Streak erreicht', '🔥', 'streak', 30, NULL, 5),
('Streak Master 60', '60-Tage-Streak erreicht', '💎', 'streak', 60, NULL, 6),
('Streak Master 90', '90-Tage-Streak erreicht', '👑', 'streak', 90, NULL, 7),
('Streak Master 180', '180-Tage-Streak erreicht', '🏆', 'streak', 180, NULL, 8),
('Streak Master 365', 'Ein ganzes Jahr Streak!', '🌟', 'streak', 365, NULL, 9),
('Perfect Day', 'Ersten perfekten Tag geschafft', '✨', 'perfect_day', 1, NULL, 10),
('Perfect Week', '7 Perfect Days am Stück', '🌈', 'perfect_days_total', 7, NULL, 11),
('Perfect 30', '30 Perfect Days insgesamt', '🎯', 'perfect_days_total', 30, NULL, 12),
('Pump Fiction Star', '1.000 Push-Ups insgesamt', '⭐', 'lifetime_total', 1000, 'Push-Ups', 13),
('Push-Up Legend', '5.000 Push-Ups insgesamt', '🦸', 'lifetime_total', 5000, 'Push-Ups', 14),
('Aquaman', '100 Liter Wasser getrunken', '🌊', 'lifetime_total', 100000, 'Wasser trinken', 15),
('Poseidon', '500 Liter Wasser getrunken', '🔱', 'lifetime_total', 500000, 'Wasser trinken', 16),
('Eisbrecher', '30 Tage kalt geduscht insgesamt', '🧊', 'lifetime_total', 30, 'Kalt duschen', 17),
('Eiskönig', '100 Tage kalt geduscht', '❄️', 'lifetime_total', 100, 'Kalt duschen', 18),
('Marathon', '42.195 Schritte an einem Tag', '🏃', 'single_day_max', 42195, 'Schritte', 19),
('Ultramarathon', '100.000 Schritte an einem Tag', '🦅', 'single_day_max', 100000, 'Schritte', 20),
('Iron Plank', '1 Stunde Plank insgesamt', '🪨', 'lifetime_total', 3600, 'Plank', 21),
('Steel Plank', '5 Stunden Plank insgesamt', '⚙️', 'lifetime_total', 18000, 'Plank', 22),
('Clean Machine', '30 Tage Clean Eating am Stück', '🥦', 'consecutive_days', 30, 'Clean Eating', 23),
('Zen Master', '100 Stunden meditiert insgesamt', '☯️', 'lifetime_total', 6000, 'Meditation/Stretching', 24),
('Schlafmütze', '30 Nächte 8+ Stunden geschlafen', '🛏️', 'days_above', 30, 'Schlaf:8', 25),
('Fastenprofi', '30 Tage 16+ Stunden gefastet', '🕐', 'days_above', 30, 'Intervallfasten:16', 26),
('Nachtragungsprofi', '10x den Vortag nachgetragen', '😅', 'backfill_count', 10, NULL, 27),
('Abstimmungskönig', '6 Monate in Folge abgestimmt', '🗳️', 'voting_streak', 6, NULL, 28),
('Trendsetter', 'Einen Challenge-Vorschlag erfolgreich durchgebracht', '💡', 'proposal_accepted', 1, NULL, 29),
('Wochensieger', 'Zum ersten Mal Wochensieger', '🏆', 'weekly_winner', 1, NULL, 30);

-- MOTIVATION QUOTES (60)
INSERT INTO `motivation_quotes` (`quote_text`, `context_type`) VALUES
('Nicht aufhören! Tag {streak} deiner Streak – du bist eine Maschine! 🔥', 'streak'),
('Tag {streak} und kein Ende in Sicht. Respekt! 💪', 'streak'),
('{streak} Tage am Stück – der Schweinehund hat Angst vor dir! 🐕', 'streak'),
('Deine Streak brennt heller als die Sonne. Weiter so! ☀️', 'streak'),
('Streak-Alarm! {streak} Tage – du bist nicht aufzuhalten! 🚀', 'streak'),
('{streak} Tage? Das ist kein Hobby mehr, das ist Lifestyle! 😎', 'streak'),
('Die anderen können deine Staubwolke sehen. {streak} Tage Streak! 💨', 'streak'),
('Gestern war nicht dein Tag? Heute wird\'s besser! 💪', 'no_streak'),
('Jede Streak beginnt mit Tag 1. Heute ist dein Tag 1! 🌅', 'no_streak'),
('Hinfallen ist okay. Liegenbleiben nicht. Los geht\'s! 🥊', 'no_streak'),
('Der Schweinehund hat gestern gewonnen? Revanche! 🐗', 'no_streak'),
('Neuer Tag, neue Chance. Die Streak wartet auf dich! 🔥', 'no_streak'),
('Aufstehen, Krone richten, weitermachen. Du packst das! 👑', 'no_streak'),
('Auch Legenden haben schlechte Tage. Aber sie kommen zurück! 🦁', 'no_streak'),
('Platz {rank}? Da geht noch was! Zeig denen wer hier pumpt! 💥', 'behind'),
('Du bist weiter hinten als gewollt? Zeit für die Aufholjagd! 🏎️', 'behind'),
('Die vor dir schlafen auch mal. Nutz jede Chance! ⚡', 'behind'),
('Platz {rank} ist nicht dein Zuhause. Kletter hoch! 🧗', 'behind'),
('Die Tabelle von unten lesen ist auch eine Perspektive... aber lass uns das ändern! 📈', 'behind'),
('Underdog-Story incoming? Das Leaderboard wartet auf dein Comeback! 🎬', 'behind'),
('Nr. 1 – und jetzt Abstand halten! 👑', 'leading'),
('Ganz oben ist die Luft dünn. Aber du atmest locker! 🏔️', 'leading'),
('Die Spitze steht dir gut. Bleib da! 🥇', 'leading'),
('Leader of the Pack! Die anderen jagen – du führst! 🐺', 'leading'),
('An der Spitze ist es einsam? Genieß die Aussicht! 🌄', 'leading'),
('Willkommen bei Pumpfiction! Dein Fitness-Abenteuer beginnt jetzt! 🎮', 'new_user'),
('Frisch dabei? Perfekt. Jede Legende hat mal angefangen! 🌱', 'new_user'),
('Erster Tag bei Pumpfiction? Mach ihn zu einem guten! ⭐', 'new_user'),
('Hey Frischling! Die Community freut sich auf deine Gains! 💪', 'new_user'),
('Discipline is choosing between what you want now and what you want most. 🎯', 'general'),
('Der beste Zeitpunkt anzufangen war gestern. Der zweitbeste ist jetzt! ⏰', 'general'),
('Dein Körper kann fast alles. Es ist dein Kopf, den du überzeugen musst. 🧠', 'general'),
('Schweiß ist Fett, das weint. Lass es fließen! 💦', 'general'),
('Es gibt keine Abkürzung. Aber der Weg lohnt sich! 🛤️', 'general'),
('Push harder than yesterday if you want a different tomorrow. 🔥', 'general'),
('Erfolg ist kein Zufall. Erfolg ist eine Gewohnheit! 🏆', 'general'),
('Du musst nicht perfekt sein. Du musst nur anfangen! 🚀', 'general'),
('Results happen over time, not overnight. Keep going! ⏳', 'general'),
('Jeder Champion war mal ein Anfänger, der nicht aufgegeben hat. 🥊', 'general'),
('Die einzige schlechte Übung ist die, die nicht stattgefunden hat. 🎯', 'general'),
('Wenn es einfach wäre, würde es jeder machen! 💎', 'general'),
('Deine Limits existieren nur in deinem Kopf. Spreng sie! 💥', 'general'),
('Ein Workout dauert eine Stunde. Motivation hält den ganzen Tag! ☀️', 'general'),
('Tu es für das Gefühl danach. Du wirst es nicht bereuen! 😌', 'general'),
('Motivation bringt dich ins Gym. Gewohnheit hält dich dort! 🏋️', 'general'),
('Der Schmerz von heute ist die Stärke von morgen! 💪', 'general'),
('PERFECT DAY! Alle Challenges geschafft – Legende! 🌟', 'perfect_day'),
('Perfekter Tag! So sieht Disziplin aus! 💎', 'perfect_day'),
('100% heute! Du bist in der Zone! 🎯', 'perfect_day'),
('Makellos! Dein Perfect Day strahlt heller als alles! ✨', 'perfect_day'),
('Du bist zurück! Die Pause ist vorbei – let\'s go! 🔄', 'comeback'),
('Comeback-Time! Zeig allen, dass du noch da bist! 🦸', 'comeback'),
('Back in the game! Jetzt erst recht! 💪', 'comeback'),
('Pause beendet? Gut. Die Challenges warten auf dich! 🎮', 'comeback'),
('Die Rückkehr des Kriegers! Willkommen zurück! ⚔️', 'comeback'),
('Heute ist ein guter Tag, um ein Beast zu sein! 🦁', 'general'),
('Less talk, more action. Los! 🏃', 'general'),
('Dein Future Self wird dir danken. Pump it! 💪', 'general'),
('Nicht jeder Tag ist gut. Aber in jedem Tag steckt was Gutes! 🌈', 'general'),
('Mach es für dich. Nicht für das Leaderboard. Okay... auch für das Leaderboard. 😏', 'general');
